version: "3.8"
services:
  db:
    image: postgis/postgis:9.5-3.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: shops
    volumes:
      - ./migrations/sql:/docker-entrypoint-initdb.d/