version: "3.8"
services:
  db:
    image: postgis/postgis:9.5-3.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - ./migrations/sql:/docker-entrypoint-initdb.d/